---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  hosts:
  - "*"
  gateways:
  {{- range $v := .Values.virtualService.gateways }}
  - {{ $v }}
  {{- end }}
  http:
  - route:
    - destination:
        host: {{ .Values.service.name }}
        port:
          number: 80  