---
apiVersion: v1
kind: Service
metadata:
  name: up-and-running
  namespace: app-team
spec:
  type: ClusterIP
  selector:
    app: up-and-running
  ports:
  - name: http
    port: 80
    targetPort: 8080