# Default values for cluster-ops.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

global: 
  labels:
    project: gke-at-scale
    region: 

autoneg: 
  serviceAccount:
    annotations:
      