---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: demo
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: us-docker.pkg.dev/google-samples/containers/gke/whereami:v1.2.20
        ports:
        - containerPort: 8080
        env:
        - name: CUSTOMER
          value: "Hello from the environment"
        - name: COLOR_PRIMARY
          value: "#000000"
        - name: COLOR_SECONDARY
          value: "#5f5f61"
        - name: COLOR_BACKGROUND
          value: "#FFFFFF"
        - name: LOCATION
          value: "europe-west6"
        - name: PLATFORM
          value: "GKE Autopilot"